version: "3.2"
services:
    # booking:
    #   image: vptv1310/flightapp:booking
    #   tty: true
    #   ports:
    #     - "5000:5000"
    #   expose:
    #     - "5000"

    flight:
        image: vptv1310/flightapp:flight
        tty: true
        ports:
          - "5001:5001"
        expose:
          - "5001"

    passenger:
        image: vptv1310/flightapp:passenger
        tty: true
        ports:
          - "5002:5002"
        expose:
          - "5002"
     
    pricing:
        image: vptv1310/flightapp:pricing
        tty: true
        ports:
          - "5003:5003"
        expose:
          - "5003"

    # billing:
    #   image: vptv1310/flightapp:billing
    #   tty: true
    #   ports:
    #     - "5004:5004"
    #   expose:
    #     - "5004"

    app:
        image: vptv1310/flightapp:app
        tty: true
        ports:
          - "8000:8000"
        expose:
          - "8000"

